In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
# Read the Iris dataset
data = pd.read_csv("iris.csv")
data.head(5)

# Drop the "Id" column and encode the target variable
data = data.drop("Id", axis=1)
data = data[data["Species"].isin(["Iris-setosa", "Iris-versicolor"])]
data["Species"] = np.where(data["Species"] == "Iris-setosa", 0, 1)
print(data["Species"])
display(data)

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: Species, Length: 100, dtype: int32


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0             5.1           3.5            1.4           0.2        0
1             4.9           3.0            1.4           0.2        0
2             4.7           3.2            1.3           0.2        0
3             4.6           3.1            1.5           0.2        0
4             5.0           3.6            1.4           0.2        0
..            ...           ...            ...           ...      ...
95            5.7           3.0            4.2           1.2        1
96            5.7           2.9            4.2           1.3        1
97            6.2           2.9            4.3           1.3        1
98            5.1           2.5            3.0           1.1        1
99            5.7           2.8            4.1           1.3        1

[100 rows x 5 columns]

In [3]:
# Shuffle the rows
np.random.seed(42)  # for reproducibility
data = data.sample(frac=1).reset_index(drop=True)

# Split the data into training and test sets
x_train = data.iloc[:80, :-1].values
x_test = data.iloc[80:, :-1].values

y_train = data.iloc[:80, -1].values
y_test = data.iloc[80:, -1].values

print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)


(80, 4) (20, 4) (80,) (20,)


In [4]:
# Standardize the features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [5]:
# Add a bias term to the input features
x_train = np.c_[np.ones(x_train.shape[0]), x_train]
x_test = np.c_[np.ones(x_test.shape[0]), x_test]
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)


(80, 5) (20, 5) (80,) (20,)


In [6]:
print(x_test)

[[ 1.          1.09932891 -0.43764323  1.34172064  1.1474489 ]
 [ 1.         -0.03025676 -0.23047484  1.20204901  1.32534795]
 [ 1.         -0.83710367 -0.02330644 -0.89302552 -1.1652388 ]
 [ 1.         -1.15984243  0.18386195 -0.8231897  -0.98733975]
 [ 1.         -0.83710367 -0.23047484 -0.96286133 -0.98733975]
 [ 1.          2.39028396 -0.02330644  1.48139228  1.32534795]
 [ 1.         -0.5143649   1.21970391 -0.89302552 -0.63154164]
 [ 1.         -1.15984243  0.18386195 -1.03269715 -0.98733975]
 [ 1.         -0.5143649   0.39103034 -0.75335388 -0.45364259]
 [ 1.          1.42206768 -1.68065358  1.13221319  0.96954984]
 [ 1.          1.09932891 -0.23047484  1.27188483  1.1474489 ]
 [ 1.          1.58343706 -0.43764323  1.06237737  0.96954984]
 [ 1.          2.0675452  -0.02330644  1.34172064  1.32534795]
 [ 1.          0.61522077 -0.85198001  0.7830341   0.79165079]
 [ 1.         -0.03025676  0.59819873 -0.75335388 -0.98733975]
 [ 1.         -0.67573429 -2.30215876  0.50369083  0.43

In [7]:
def initialize_weights():
    return np.zeros(x_train.shape[1])


In [8]:
def predict(weights, inputs):
    return np.dot(inputs, weights)

In [9]:
def mse_loss(predictions, targets):
    return np.mean((predictions - targets) ** 2)

In [10]:
def update_weights(weights, inputs, predictions, targets, learning_rate):
    gradient = np.dot(inputs.T, predictions - targets) / len(targets)
    weights -= learning_rate * gradient
    return weights


In [11]:
def train_perceptron(x_train, y_train, learning_rate, epochs):
    weights = initialize_weights()
    print(weights)

    for epoch in range(epochs):
        predictions = predict(weights, x_train)
        print(f"predictions epoch -{epoch} ", predictions)
        loss = mse_loss(predictions, y_train)
        print(f"loss epoch -{epoch} ", loss)
        
        # Check for convergence (you can modify this condition based on your requirements)
        if loss < 0.001:
            print(f"Converged at epoch {epoch + 1}. MSE Loss: {loss}")
            break

        weights = update_weights(weights, x_train, predictions, y_train, learning_rate)
        print(f"weights epoch -{epoch} ", weights)

    return weights

In [12]:
def step_function(predictions):
    return np.where(predictions <= 0, 0, 1)

# Train the perceptron
weights = train_perceptron(x_train, y_train, learning_rate=0.0001, epochs=10)

# Test the trained perceptron on the test set
test_predictions = step_function(predict(weights, x_test))
accuracy = np.mean(test_predictions == y_test) * 100
print(f"Accuracy: {accuracy}%")

[0. 0. 0. 0. 0.]
predictions epoch -0  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
loss epoch -0  0.475
weights epoch -0  [ 4.75000000e-05  3.60811852e-05 -3.45129593e-05  4.83678507e-05
  4.78326082e-05]
predictions epoch -1  [ 2.61058645e-04  1.97862610e-04  2.26371602e-04 -6.58609151e-05
 -8.01952562e-05 -8.21252641e-05 -1.42426287e-04  1.66938248e-04
 -8.61080514e-05 -9.26530668e-05 -6.05258575e-05 -7.47646684e-05
  2.12182313e-04 -1.19413433e-04  1.81414485e-04 -1.05625460e-04
  2.73335663e-04  2.85497020e-04 -8.28796666e-05 -4.76393170e-05
  1.90646478e-04  1.57012857e-04 -6.75511027e-05 -1.15337682e-04
  1.68988460e-04 -1.01672064e-04 -9.33438980e-05  1.73363058e-04
 -8.08294540e-05  2.77560837e-04 -9.62146513e-05 -1.00315077e-04
  1.90741835e-04 -7.96806739e-05  1.19577832e-04 -7.